#!/bin/sh
#
# 2011 Steven Armstrong (steven-cdist at armstrong.cc)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

# set defaults
if [ -f "$__object/parameter/uri" ]; then
   uri="$(cat "$__object/parameter/uri")"
else
   uri="$__object_id"
   echo "$uri" > "$__object/parameter/uri"
fi

if [ -f "$__object/parameter/target" ]; then
   target="$(cat "$__object/parameter/target")"
else
   target="/target"
   echo "$target" > "$__object/parameter/target"
fi
