#!/bin/sh
#
# 2011 Steven Armstrong (steven-cdist at armstrong.cc)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

fstab="$__object/files/fstab"
for object in $(find "$__global/object/__install_mount" -path "*.cdist"); do
   device="$(cat "$object/parameter/device")"
   dir="$(cat "$object/parameter/dir")"
   prefix="$(cat "$object/parameter/prefix")"
   type="$(cat "$object/parameter/type")"
   if [ -f "$__object/parameter/options" ]; then
      options="$(cat "$object/parameter/options")"
   else
      options="defaults"
   fi
   dump=0
   case "$type" in
      swap|tmpfs)
         pass=0
         dir="$type"
      ;;
      *)
         pass=1
      ;;
   esac
   echo "$device $dir $type $options $dump $pass" >> "$fstab"
done
