#!/bin/sh
#
# 2015 Steven Armstrong (steven-cdist at armstrong.cc)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

if [ -f "$__object/parameter/name" ]; then
   name="$(cat "$__object/parameter/name")"
else
   name="$__object_id"
fi

state_should="$(cat "$__object/parameter/state")"
state_is="$(test -s "$__object/explorer/version" && echo present || echo absent)"

if [ "$state_is" = "$state_should" ]; then
   # Nothing to do
   exit 0
fi

case "$state_should" in
   present)
      printf 'pkgin -y install %s\n' "$name"
   ;;
   absent)
      printf 'pkgin -y remove %s\n' "$name"
   ;;
esac
